# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-Travel-OTA
version:      0.901
version_from: 
installdirs:  site
requires:
    App::Context:                  0.01
    App::Options:                  0.01
    SOAP::Lite:                    0.01
    XML::DOM:                      0.01
    XML::Simple:                   0.01
    XML::XPath:                    0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
